name: Build

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  docker:
    permissions:
      contents: read
      packages: write
      id-token: write

    name: docker build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup depot CLI
        uses: depot/setup-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run docker build
        uses: depot/build-push-action@v1
        with:
          push: true
          file: Dockerfile
          tags: |
            stayallive/hera
            ghcr.io/stayallive/hera
          context: .
          platforms: |
            linux/amd64
